{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","roleHeading":"Case","symbolKind":"case","title":"IdVerificationError.clientError","modules":[{"name":"IdVerification365id"}]},"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"title":"IdVerificationError","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"url":"\/documentation\/idverification365id\/idverificationerror","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"url":"\/documentation\/idverification365id","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","title":"IdVerification365id","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","kind":"symbol","title":"IdVerificationError.clientError","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"type":"topic","abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","role":"symbol"}}}