{"metadata":{"modules":[{"name":"IdVerification365id"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","roleHeading":"Case","title":"IdVerificationError.clientError","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"},"sections":[],"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","title":"IdVerificationError","abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"code":"IdVerificationEventDelegate","type":"codeVoice"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"IdVerificationError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerror","navigatorTitle":[{"text":"IdVerificationError","kind":"identifier"}],"role":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"title":"IdVerificationError.clientError","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","role":"symbol","type":"topic","kind":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","kind":"symbol","url":"\/documentation\/idverification365id","title":"IdVerification365id"}}}