{"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"metadata":{"externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"modules":[{"name":"IdVerification365id"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","title":"IdVerificationError.clientError"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"},"abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"title":"IdVerificationError","abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"code":"onError(error:)","type":"codeVoice"},{"type":"text","text":" method in the "},{"code":"IdVerificationEventDelegate","type":"codeVoice"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/idverification365id\/idverificationerror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"IdVerificationError","kind":"identifier"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","kind":"symbol","title":"IdVerificationError.clientError","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","role":"collection","abstract":[],"kind":"symbol","title":"IdVerification365id","type":"topic","url":"\/documentation\/idverification365id"}}}