{"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"},"kind":"symbol","metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"roleHeading":"Case","title":"IdVerificationError.clientError","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","role":"symbol","modules":[{"name":"IdVerification365id"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"url":"\/documentation\/idverification365id","title":"IdVerification365id","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","kind":"symbol","type":"topic","role":"collection"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdVerificationError"}],"role":"symbol","url":"\/documentation\/idverification365id\/idverificationerror","navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"title":"IdVerificationError"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"kind":"symbol","title":"IdVerificationError.clientError","type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"}}}