{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","interfaceLanguage":"swift"},"abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"metadata":{"symbolKind":"case","title":"IdVerificationError.clientError","modules":[{"name":"IdVerification365id"}],"externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"roleHeading":"Case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"kind":"symbol","url":"\/documentation\/idverification365id","type":"topic","role":"collection","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","abstract":[],"title":"IdVerification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"url":"\/documentation\/idverification365id\/idverificationerror","type":"topic","kind":"symbol","title":"IdVerificationError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationError"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"title":"IdVerificationError.clientError","kind":"symbol","type":"topic","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"role":"symbol"}}}