{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"roleHeading":"Case","title":"IdVerificationError.clientError","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","symbolKind":"case","role":"symbol","modules":[{"name":"IdVerification365id"}]},"abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"sections":[],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerror","role":"symbol","navigatorTitle":[{"text":"IdVerificationError","kind":"identifier"}],"title":"IdVerificationError","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"code":"onError(error:)","type":"codeVoice"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"title":"IdVerificationError.clientError","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"url":"\/documentation\/idverification365id","type":"topic","kind":"symbol","title":"IdVerification365id","role":"collection","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id"}}}