{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","symbolKind":"case","title":"IdVerificationError.clientError","modules":[{"name":"IdVerification365id"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"url":"\/documentation\/idverification365id","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","role":"collection","type":"topic","title":"IdVerification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","kind":"symbol","role":"symbol","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"title":"IdVerificationError.clientError"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"kind":"symbol","title":"IdVerificationError","type":"topic","abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"code":"IdVerificationEventDelegate","type":"codeVoice"}],"url":"\/documentation\/idverification365id\/idverificationerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationError"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","role":"symbol","navigatorTitle":[{"text":"IdVerificationError","kind":"identifier"}]}}}