{"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"]}],"metadata":{"externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","title":"onError(_:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"IdVerification365id"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"text":")","kind":"text"}],"required":true},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"IdVerificationErrorBundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"recieved."}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"url":"\/documentation\/idverification365id","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","title":"IdVerification365id","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"navigatorTitle":[{"kind":"identifier","text":"IdVerificationEventDelegate"}],"type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","url":"\/documentation\/idverification365id\/idverificationeventdelegate","role":"symbol","abstract":[{"text":"IdVerification SDK event Delegate that is informing about various events","type":"text"}],"title":"IdVerificationEventDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationEventDelegate"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"abstract":[{"text":"This is a error bundle used to present errors generated from the IdVerification SDK","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","role":"symbol","url":"\/documentation\/idverification365id\/idverificationerrorbundle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IdVerificationErrorBundle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationErrorBundle"}],"type":"topic","title":"IdVerificationErrorBundle"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"title":"onError(_:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"type":"text","text":" "},{"text":"recieved.","type":"text"}],"url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"text":")","kind":"text"}],"required":true}}}