{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"IdVerification365id"}],"title":"onError(_:)","externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","roleHeading":"Instance Method","required":true},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"recieved."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","interfaceLanguage":"swift"},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"type":"topic","required":true,"kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"type":"text","text":" "},{"text":"recieved.","type":"text"}],"title":"onError(_:)"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"title":"IdVerificationEventDelegate","url":"\/documentation\/idverification365id\/idverificationeventdelegate","role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","navigatorTitle":[{"text":"IdVerificationEventDelegate","kind":"identifier"}],"abstract":[{"text":"IdVerification SDK event Delegate that is informing about various events","type":"text"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationEventDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","role":"collection","title":"IdVerification365id","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","title":"IdVerificationErrorBundle","role":"symbol","kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerrorbundle","type":"topic","abstract":[{"text":"This is a error bundle used to present errors generated from the IdVerification SDK","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"identifier"}],"navigatorTitle":[{"text":"IdVerificationErrorBundle","kind":"identifier"}]}}}