{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"IdVerificationErrorBundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"text":" ","type":"text"},{"text":"recieved.","type":"text"}],"metadata":{"externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","required":true,"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"text":")","kind":"text"}],"role":"symbol","title":"onError(_:)","modules":[{"name":"IdVerification365id"}]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","type":"topic","kind":"symbol","abstract":[{"text":"IdVerification SDK event Delegate that is informing about various events","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationEventDelegate"}],"navigatorTitle":[{"text":"IdVerificationEventDelegate","kind":"identifier"}],"url":"\/documentation\/idverification365id\/idverificationeventdelegate","title":"IdVerificationEventDelegate"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","role":"collection","type":"topic","title":"IdVerification365id","url":"\/documentation\/idverification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"type":"text","text":" "},{"text":"recieved.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","required":true,"role":"symbol","url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onError(_:)"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"kind":"symbol","navigatorTitle":[{"text":"IdVerificationErrorBundle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationErrorBundle"}],"abstract":[{"type":"text","text":"This is a error bundle used to present errors generated from the IdVerification SDK"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","url":"\/documentation\/idverification365id\/idverificationerrorbundle","type":"topic","role":"symbol","title":"IdVerificationErrorBundle"}}}